"""add content_type column

Revision ID: 5d90090cbdcc
Revises: 32c95ad76b1d
Create Date: 2023-07-25 19:17:55.951255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d90090cbdcc'
down_revision = '32c95ad76b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
