"""add time_created column

Revision ID: 807a498f3b26
Revises: 5d90090cbdcc
Create Date: 2023-07-25 19:19:16.457150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807a498f3b26'
down_revision = '5d90090cbdcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
